"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ChadTech.py']
PACKAGES = ['PIL','pygame']
RESOURCES =['chars6x8','chars12x16','introscreen.PNG','selected.PNG','thumbnail.PNG']
OPTIONS = {
    'packages': PACKAGES,
    'resources': RESOURCES,
    'iconfile': 'thumbnail.icns',
    'plist': {
        'CFBundleName': 'ChadTech',
        'CFBundleShortVersionString':'0.3.0', # must be in X.X.X format
        'CFBundleVersion': '0.3.0',
        'CFBundleIdentifier':'com.chadtech.chadtechv0', #optional
        'NSHumanReadableCopyright': '@ ChadTech ChadTech 2014', #optional
        'CFBundleDevelopmentRegion': 'English', #optional - English is default
        'CFBundleDocumentTypes':[
        dict(
        CFBundleTypeExtensions=['png'],
        CFBundleTypeIconFile='thumbnail.icns',
        CFBundleTypeRole='Editor',
        )
        ],
    }
}

setup(
    setup_requires=['py2app'],
    app=APP,
    options={'py2app': OPTIONS},
)
